version: "0.1"
services:
  app:
    build: .
    container_name: Inge_Soft_Container
    ports:
      - 19006:19006
      - 19001:19001
      - 19002:19002
      - 8081:8081
    volumes:
      - ./components:/app/components
      - ./lib:/app/lib
      - ./screens:/app/screens
      - ./App.tsx:/app/App.tsx
      - ./tests:/app/tests
      - ./jest.config.js:/app/jest.config.js
      - ./package.json:/app/package.json
      - ./babel.config.js:/app/babel.config.js
    tty: true